language: node_js
sudo: false
node_js:
- '4'
cache:
  apt: true
  directories:
  - node_modules
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  ssh_known_hosts: github.com
script:
- npm run build
deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_721768e2df7d_key -iv $encrypted_721768e2df7d_iv
  -in id_rsa.enc -out id_rsa -d
