title: WE-VUE
subtitle: "weui1.x + vue2.x + webpack2 = we-vue"
description: "一套简洁高效的 weui 样式的 vue 组件库"
author: tianyong90
language: zh-cn
multi_language: false
timezone: Asia/Shanghai
url: http://wevue.org
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

server:
  port: 4001

theme: navy
deploy:
  type: git
  repo: git@github.com:tianyong90/wevue.org.git
  branch: master

disqus_shortname: false
weibo: 1707227001
github: tianyong90/we-vue

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-emoji  # add emoji
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: false
    permalinkClass: header-anchor
    permalinkSymbol: ¶
